# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/disturbed/UnrealEngine

TARGETS = \
	Destiny3-Android-DebugGame  \
	Destiny3-Android-Development  \
	Destiny3-Android-Shipping  \
	Destiny3-Linux-DebugGame  \
	Destiny3-Linux-Development  \
	Destiny3-Linux-Shipping  \
	Destiny3-LinuxArm64-DebugGame  \
	Destiny3-LinuxArm64-Development  \
	Destiny3-LinuxArm64-Shipping  \
	Destiny3 \
	Destiny3Editor-Linux-DebugGame  \
	Destiny3Editor-Linux-Development  \
	Destiny3Editor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Destiny3Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Destiny3Editor-Linux-Debug


Destiny3-Android-DebugGame:
	 $(BUILD) Destiny3 Android DebugGame  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-Android-Development:
	 $(BUILD) Destiny3 Android Development  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-Android-Shipping:
	 $(BUILD) Destiny3 Android Shipping  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-Linux-DebugGame:
	 $(BUILD) Destiny3 Linux DebugGame  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-Linux-Development:
	 $(BUILD) Destiny3 Linux Development  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-Linux-Shipping:
	 $(BUILD) Destiny3 Linux Shipping  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-LinuxArm64-DebugGame:
	 $(BUILD) Destiny3 LinuxArm64 DebugGame  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-LinuxArm64-Development:
	 $(BUILD) Destiny3 LinuxArm64 Development  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3-LinuxArm64-Shipping:
	 $(BUILD) Destiny3 LinuxArm64 Shipping  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3: Destiny3-Linux-Development

Destiny3Editor-Linux-DebugGame:
	 $(BUILD) Destiny3Editor Linux DebugGame  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3Editor-Linux-Development:
	 $(BUILD) Destiny3Editor Linux Development  -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" $(ARGS)

Destiny3Editor: Destiny3Editor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/disturbed/GitRepos/Looter/Destiny3.uproject" -Game 

.PHONY: $(TARGETS)
